120 text messages too long
grassrootsgrocery/admin-portal pull request #124
Opened 2023-08-13 15:31 UTC by 6mp

## Description of this change
- Refactor to use SendTextMesssageButton.tsx
- Shows popup on other two send message buttons #121 
- Last text messages sent has fixed height and scrolls now #120 

## Screenshots

### Before this PR:
![](https://user-images.githubusercontent.com/15386131/260265550-13014f73-91de-46c4-a7fc-bb6fd110e382.png)

### After this PR:
<img width="1722" alt="image" src="https://github.com/grassrootsgrocery/admin-portal/assets/30198937/ae2a307e-632c-4aba-bf96-6cbee171d620">

## Checklist
- [ ] Added link to existing Issue (created issue if there wasn't one already)
- [ ] Added screenshots before/after for UI changes
- [ ] PR is from branch pushed to this repo so that it will trigger Railway PR deployment
- [ ] Code follows the style of this project

2023-08-13 15:47 UTC, mattsahn requested changes
This is great, @6mp! A couple minor things on the functionality side:
- For the timestamp, we don't need seconds included. So "12:55:00 PM" should just be "12:55 PM"
- Do the sorting in reverse order instead so that the most recent text is at the very top where it can be seen right away. The user can scroll down to see older messages.

![image](https://github.com/grassrootsgrocery/admin-portal/assets/15386131/b25bfddc-cb4d-414f-bc66-b481678692dc)

2023-08-13 16:07 UTC, 6mp commented
@mattsahn I addressed those two things, the order is reversed and I dropped the seconds from the time

2023-08-13 16:22 UTC, mattsahn commented on client/src/pages/DriverLocationInfo/SendTextMesssageButton.tsx
Seems like this file should live somewhere more generic than within /pages/DriverLocationInfo/ since it's no longer tied to any single page and will be used anywhere we send a text message around the app. Not sure what the best home is, but something like /client/, /client/src/, or /client/src/components/ perhaps?

2023-08-13 16:22 UTC, mattsahn commented
> @mattsahn I addressed those two things, the order is reversed and I dropped the seconds from the time

looks good now. thanks.

2023-08-13 18:21 UTC, 6mp commented on client/src/pages/DriverLocationInfo/SendTextMesssageButton.tsx
You are correct, I have relocated the file to ` /client/src/components/`.

2023-08-14 01:06 UTC, mattsahn approved these changes
lgtm

2023-08-14 01:06 UTC, merged